// Code generated by protoc-gen-go. DO NOT EDIT.
// source: default.proto

package _default

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string               `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IconImagePath        string               `protobuf:"bytes,3,opt,name=icon_image_path,json=iconImagePath,proto3" json:"icon_image_path,omitempty"`
	BackgroundImagePath  string               `protobuf:"bytes,4,opt,name=background_image_path,json=backgroundImagePath,proto3" json:"background_image_path,omitempty"`
	Profile              string               `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`
	Email                string               `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1e5780510d421cc, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetIconImagePath() string {
	if m != nil {
		return m.IconImagePath
	}
	return ""
}

func (m *User) GetBackgroundImagePath() string {
	if m != nil {
		return m.BackgroundImagePath
	}
	return ""
}

func (m *User) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1e5780510d421cc, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "default.User")
	proto.RegisterType((*GetUserRequest)(nil), "default.GetUserRequest")
}

func init() { proto.RegisterFile("default.proto", fileDescriptor_b1e5780510d421cc) }

var fileDescriptor_b1e5780510d421cc = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xb1, 0x4f, 0xc2, 0x40,
	0x14, 0xc6, 0x43, 0x05, 0x6a, 0x1f, 0x82, 0xc9, 0xa9, 0xe1, 0xc2, 0x22, 0x32, 0x18, 0x5c, 0x4a,
	0xc4, 0xc9, 0x11, 0x35, 0x31, 0x2c, 0xc6, 0xa0, 0x2e, 0x2e, 0xcd, 0xd1, 0x7b, 0x94, 0x8b, 0x2d,
	0x57, 0xaf, 0x57, 0x13, 0xff, 0x71, 0x67, 0xd3, 0xeb, 0x1d, 0xe8, 0xc4, 0xf8, 0x7d, 0xef, 0xf7,
	0x6b, 0xfa, 0xfa, 0x0a, 0x5d, 0x8e, 0x2b, 0x56, 0xa6, 0x3a, 0xcc, 0x95, 0xd4, 0x92, 0xf8, 0x36,
	0x0e, 0xce, 0x13, 0x29, 0x93, 0x14, 0x27, 0xa6, 0x5e, 0x96, 0xab, 0x89, 0x16, 0x19, 0x16, 0x9a,
	0x65, 0x79, 0x4d, 0x8e, 0x7e, 0x3c, 0x68, 0xbe, 0x15, 0xa8, 0x48, 0x0f, 0x3c, 0xc1, 0x69, 0x63,
	0xd8, 0x18, 0x07, 0x0b, 0x4f, 0x70, 0x72, 0x01, 0x47, 0x5c, 0x14, 0x79, 0xca, 0xbe, 0xa3, 0x0d,
	0xcb, 0x90, 0x7a, 0x66, 0xd2, 0xb1, 0xdd, 0x13, 0xcb, 0x90, 0x5c, 0xc2, 0xb1, 0x88, 0xe5, 0x26,
	0x12, 0x19, 0x4b, 0x30, 0xca, 0x99, 0x5e, 0xd3, 0x03, 0x43, 0x75, 0xab, 0x7a, 0x5e, 0xb5, 0xcf,
	0x4c, 0xaf, 0xc9, 0x14, 0xce, 0x96, 0x2c, 0xfe, 0x48, 0x94, 0x2c, 0x37, 0xfc, 0x2f, 0xdd, 0x34,
	0xf4, 0xc9, 0x6e, 0xb8, 0x73, 0x28, 0xf8, 0xb9, 0x92, 0x2b, 0x91, 0x22, 0x6d, 0x19, 0xca, 0x45,
	0x72, 0x0a, 0x2d, 0xcc, 0x98, 0x48, 0x69, 0xdb, 0xf4, 0x75, 0x20, 0xb7, 0x00, 0xb1, 0x42, 0xa6,
	0x91, 0x47, 0x4c, 0xd3, 0xc3, 0x61, 0x63, 0xdc, 0x99, 0x0e, 0xc2, 0x7a, 0xfb, 0xd0, 0x6d, 0x1f,
	0xbe, 0xba, 0xed, 0x17, 0x81, 0xa5, 0x67, 0xba, 0x52, 0xcb, 0x9c, 0x3b, 0x35, 0xd8, 0xaf, 0x5a,
	0xba, 0x56, 0x39, 0xa6, 0x68, 0x55, 0xd8, 0xaf, 0x5a, 0x7a, 0xa6, 0x47, 0x57, 0xd0, 0x7b, 0x44,
	0x5d, 0x7d, 0xfa, 0x05, 0x7e, 0x96, 0x58, 0x68, 0xd2, 0x07, 0xbf, 0x2c, 0x50, 0x45, 0xdb, 0x33,
	0xb4, 0xab, 0x38, 0xe7, 0xd3, 0x7b, 0xe8, 0x3d, 0xd4, 0xf7, 0x7c, 0x41, 0xf5, 0x25, 0x62, 0x24,
	0xd7, 0xe0, 0x5b, 0x99, 0xf4, 0x43, 0x77, 0xfa, 0xff, 0x8f, 0x1b, 0x74, 0xb7, 0x83, 0xaa, 0xbd,
	0x0b, 0xde, 0xdd, 0x4f, 0xb1, 0x6c, 0x9b, 0x37, 0xbb, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x88,
	0xa6, 0xe4, 0x93, 0x35, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DefaultServiceClient is the client API for DefaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DefaultServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
}

type defaultServiceClient struct {
	cc *grpc.ClientConn
}

func NewDefaultServiceClient(cc *grpc.ClientConn) DefaultServiceClient {
	return &defaultServiceClient{cc}
}

func (c *defaultServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/default.DefaultService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DefaultServiceServer is the server API for DefaultService service.
type DefaultServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*User, error)
}

// UnimplementedDefaultServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDefaultServiceServer struct {
}

func (*UnimplementedDefaultServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterDefaultServiceServer(s *grpc.Server, srv DefaultServiceServer) {
	s.RegisterService(&_DefaultService_serviceDesc, srv)
}

func _DefaultService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/default.DefaultService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DefaultService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "default.DefaultService",
	HandlerType: (*DefaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _DefaultService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "default.proto",
}
