// Code generated by MockGen. DO NOT EDIT.
// Source: admin_staff.go
//
// Generated by this command:
//
//	mockgen -source=admin_staff.go -destination=mock/admin_staff.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	model "github.com/abyssparanoia/rapid-go/internal/domain/model"
	input "github.com/abyssparanoia/rapid-go/internal/usecase/input"
	output "github.com/abyssparanoia/rapid-go/internal/usecase/output"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminStaffInteractor is a mock of AdminStaffInteractor interface.
type MockAdminStaffInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockAdminStaffInteractorMockRecorder
	isgomock struct{}
}

// MockAdminStaffInteractorMockRecorder is the mock recorder for MockAdminStaffInteractor.
type MockAdminStaffInteractorMockRecorder struct {
	mock *MockAdminStaffInteractor
}

// NewMockAdminStaffInteractor creates a new mock instance.
func NewMockAdminStaffInteractor(ctrl *gomock.Controller) *MockAdminStaffInteractor {
	mock := &MockAdminStaffInteractor{ctrl: ctrl}
	mock.recorder = &MockAdminStaffInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminStaffInteractor) EXPECT() *MockAdminStaffInteractorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdminStaffInteractor) Create(ctx context.Context, param *input.AdminCreateStaff) (*output.AdminCreateStaff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, param)
	ret0, _ := ret[0].(*output.AdminCreateStaff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAdminStaffInteractorMockRecorder) Create(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdminStaffInteractor)(nil).Create), ctx, param)
}

// Get mocks base method.
func (m *MockAdminStaffInteractor) Get(ctx context.Context, param *input.AdminGetStaff) (*model.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, param)
	ret0, _ := ret[0].(*model.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAdminStaffInteractorMockRecorder) Get(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdminStaffInteractor)(nil).Get), ctx, param)
}

// List mocks base method.
func (m *MockAdminStaffInteractor) List(ctx context.Context, param *input.AdminListStaffs) (*output.ListStaffs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, param)
	ret0, _ := ret[0].(*output.ListStaffs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAdminStaffInteractorMockRecorder) List(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAdminStaffInteractor)(nil).List), ctx, param)
}

// Update mocks base method.
func (m *MockAdminStaffInteractor) Update(ctx context.Context, param *input.AdminUpdateStaff) (*model.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, param)
	ret0, _ := ret[0].(*model.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAdminStaffInteractorMockRecorder) Update(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdminStaffInteractor)(nil).Update), ctx, param)
}
