// Code generated by MockGen. DO NOT EDIT.
// Source: staff_tenant.go
//
// Generated by this command:
//
//	mockgen -source=staff_tenant.go -destination=mock/staff_tenant.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	model "github.com/abyssparanoia/rapid-go/internal/domain/model"
	input "github.com/abyssparanoia/rapid-go/internal/usecase/input"
	output "github.com/abyssparanoia/rapid-go/internal/usecase/output"
	gomock "go.uber.org/mock/gomock"
)

// MockStaffTenantInteractor is a mock of StaffTenantInteractor interface.
type MockStaffTenantInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockStaffTenantInteractorMockRecorder
	isgomock struct{}
}

// MockStaffTenantInteractorMockRecorder is the mock recorder for MockStaffTenantInteractor.
type MockStaffTenantInteractorMockRecorder struct {
	mock *MockStaffTenantInteractor
}

// NewMockStaffTenantInteractor creates a new mock instance.
func NewMockStaffTenantInteractor(ctrl *gomock.Controller) *MockStaffTenantInteractor {
	mock := &MockStaffTenantInteractor{ctrl: ctrl}
	mock.recorder = &MockStaffTenantInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffTenantInteractor) EXPECT() *MockStaffTenantInteractorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStaffTenantInteractor) Create(ctx context.Context, param *input.StaffCreateTenant) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, param)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStaffTenantInteractorMockRecorder) Create(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStaffTenantInteractor)(nil).Create), ctx, param)
}

// Delete mocks base method.
func (m *MockStaffTenantInteractor) Delete(ctx context.Context, param *input.StaffDeleteTenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStaffTenantInteractorMockRecorder) Delete(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStaffTenantInteractor)(nil).Delete), ctx, param)
}

// Get mocks base method.
func (m *MockStaffTenantInteractor) Get(ctx context.Context, param *input.StaffGetTenant) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, param)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStaffTenantInteractorMockRecorder) Get(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStaffTenantInteractor)(nil).Get), ctx, param)
}

// List mocks base method.
func (m *MockStaffTenantInteractor) List(ctx context.Context, param *input.StaffListTenants) (*output.ListTenants, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, param)
	ret0, _ := ret[0].(*output.ListTenants)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStaffTenantInteractorMockRecorder) List(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStaffTenantInteractor)(nil).List), ctx, param)
}

// Update mocks base method.
func (m *MockStaffTenantInteractor) Update(ctx context.Context, param *input.StaffUpdateTenant) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, param)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStaffTenantInteractorMockRecorder) Update(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStaffTenantInteractor)(nil).Update), ctx, param)
}
