// Code generated by MockGen. DO NOT EDIT.
// Source: staff_staff.go
//
// Generated by this command:
//
//	mockgen -source=staff_staff.go -destination=mock/staff_staff.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	model "github.com/abyssparanoia/rapid-go/internal/domain/model"
	input "github.com/abyssparanoia/rapid-go/internal/usecase/input"
	output "github.com/abyssparanoia/rapid-go/internal/usecase/output"
	gomock "go.uber.org/mock/gomock"
)

// MockStaffStaffInteractor is a mock of StaffStaffInteractor interface.
type MockStaffStaffInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockStaffStaffInteractorMockRecorder
	isgomock struct{}
}

// MockStaffStaffInteractorMockRecorder is the mock recorder for MockStaffStaffInteractor.
type MockStaffStaffInteractorMockRecorder struct {
	mock *MockStaffStaffInteractor
}

// NewMockStaffStaffInteractor creates a new mock instance.
func NewMockStaffStaffInteractor(ctrl *gomock.Controller) *MockStaffStaffInteractor {
	mock := &MockStaffStaffInteractor{ctrl: ctrl}
	mock.recorder = &MockStaffStaffInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffStaffInteractor) EXPECT() *MockStaffStaffInteractorMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStaffStaffInteractor) Get(ctx context.Context, param *input.StaffGetStaff) (*model.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, param)
	ret0, _ := ret[0].(*model.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStaffStaffInteractorMockRecorder) Get(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStaffStaffInteractor)(nil).Get), ctx, param)
}

// List mocks base method.
func (m *MockStaffStaffInteractor) List(ctx context.Context, param *input.StaffListStaffs) (*output.ListStaffs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, param)
	ret0, _ := ret[0].(*output.ListStaffs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStaffStaffInteractorMockRecorder) List(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStaffStaffInteractor)(nil).List), ctx, param)
}
