// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	GooseDBVersion string
	Tenants        string
	UserRoles      string
	Users          string
}{
	GooseDBVersion: "goose_db_version",
	Tenants:        "tenants",
	UserRoles:      "user_roles",
	Users:          "users",
}
