version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - cyclop
    - decorder
    - durationcheck
    - errcheck
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - godot
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nakedret
    - nilerr
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 60
      package-average: 10
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - switch
        - map
    exhaustruct:
      include:
        - github.com/abyssparanoia/rapid-go/internal/domain/model.*
        - github.com/abyssparanoia/rapid-go/internal/usecase/input.*
        - github.com/abyssparanoia/rapid-go/internal/usecase/output.*
        - github.com/abyssparanoia/rapid-go/internal/infrastructure/mysql/internal/dbmodel.*
        - github.com/abyssparanoia/rapid-go/internal/infrastructure/spanner/internal/dbmodel.*
        - github.com/abyssparanoia/rapid-go/internal/infrastructure/grpc/pb/rapid/admin_api/v1.*
    forbidigo:
      forbid:
        - pattern: fmt\.Print.*
        - pattern: zap\.Error.*
    funlen:
      lines: 300
      statements: 100
      ignore-comments: true
    gocognit:
      min-complexity: 20
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations:
                - google.golang.org/protobuf
              reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
          - github.com/satori/go.uuid:
              recommendations:
                - github.com/google/uuid
              reason: satori's package is not maintained
          - github.com/gofrs/uuid:
              recommendations:
                - github.com/gofrs/uuid/v5
              reason: gofrs' package was not go module before v5
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: false
    inamedparam:
      skip-single-param: true
    nakedret:
      max-func-lines: 0
    perfsprint:
      strconcat: false
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    sloglint:
      no-global: all
      context: scope
    wrapcheck:
      ignore-package-globs:
        - github.com/abyssparanoia/rapid-go/internal/domain*
        - github.com/abyssparanoia/rapid-go/internal/infrastructure*
        - github.com/abyssparanoia/rapid-go/internal/usecase*
        - github.com/avast/retry-go
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - bodyclose
          - dupl
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck
        path: _test\.go
      - linters:
          - forbidigo
        path: cmd/app/main.go
    paths:
      - test-script
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
severity:
  default: error
formatters:
  enable:
    - gci
    - goimports
  exclusions:
    generated: lax
    paths:
      - test-script
      - third_party$
      - builtin$
      - examples$
