// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rapid/staff_api/v1/api_me.proto

package staff_apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignUp
type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantName    string                 `protobuf:"bytes,1,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ImageAssetId  string                 `protobuf:"bytes,3,opt,name=image_asset_id,json=imageAssetId,proto3" json:"image_asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_rapid_staff_api_v1_api_me_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpRequest) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *SignUpRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SignUpRequest) GetImageAssetId() string {
	if x != nil {
		return x.ImageAssetId
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_rapid_staff_api_v1_api_me_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

// GetMe
type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_rapid_staff_api_v1_api_me_proto_rawDescGZIP(), []int{2}
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_rapid_staff_api_v1_api_me_proto_rawDescGZIP(), []int{3}
}

func (x *GetMeResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

// GetMeTenant
type GetMeTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeTenantRequest) Reset() {
	*x = GetMeTenantRequest{}
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeTenantRequest) ProtoMessage() {}

func (x *GetMeTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeTenantRequest.ProtoReflect.Descriptor instead.
func (*GetMeTenantRequest) Descriptor() ([]byte, []int) {
	return file_rapid_staff_api_v1_api_me_proto_rawDescGZIP(), []int{4}
}

type GetMeTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeTenantResponse) Reset() {
	*x = GetMeTenantResponse{}
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeTenantResponse) ProtoMessage() {}

func (x *GetMeTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeTenantResponse.ProtoReflect.Descriptor instead.
func (*GetMeTenantResponse) Descriptor() ([]byte, []int) {
	return file_rapid_staff_api_v1_api_me_proto_rawDescGZIP(), []int{5}
}

func (x *GetMeTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// UpdateMe
type UpdateMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   *string                `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	ImageAssetId  *string                `protobuf:"bytes,2,opt,name=image_asset_id,json=imageAssetId,proto3,oneof" json:"image_asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeRequest) Reset() {
	*x = UpdateMeRequest{}
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeRequest) ProtoMessage() {}

func (x *UpdateMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeRequest) Descriptor() ([]byte, []int) {
	return file_rapid_staff_api_v1_api_me_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMeRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateMeRequest) GetImageAssetId() string {
	if x != nil && x.ImageAssetId != nil {
		return *x.ImageAssetId
	}
	return ""
}

type UpdateMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeResponse) Reset() {
	*x = UpdateMeResponse{}
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeResponse) ProtoMessage() {}

func (x *UpdateMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeResponse.ProtoReflect.Descriptor instead.
func (*UpdateMeResponse) Descriptor() ([]byte, []int) {
	return file_rapid_staff_api_v1_api_me_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMeResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

// UpdateMeTenant
type UpdateMeTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeTenantRequest) Reset() {
	*x = UpdateMeTenantRequest{}
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeTenantRequest) ProtoMessage() {}

func (x *UpdateMeTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeTenantRequest) Descriptor() ([]byte, []int) {
	return file_rapid_staff_api_v1_api_me_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMeTenantRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type UpdateMeTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeTenantResponse) Reset() {
	*x = UpdateMeTenantResponse{}
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeTenantResponse) ProtoMessage() {}

func (x *UpdateMeTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_staff_api_v1_api_me_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeTenantResponse.ProtoReflect.Descriptor instead.
func (*UpdateMeTenantResponse) Descriptor() ([]byte, []int) {
	return file_rapid_staff_api_v1_api_me_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMeTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

var File_rapid_staff_api_v1_api_me_proto protoreflect.FileDescriptor

const file_rapid_staff_api_v1_api_me_proto_rawDesc = "" +
	"\n" +
	"\x1frapid/staff_api/v1/api_me.proto\x12\x12rapid.staff_api.v1\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a$rapid/staff_api/v1/model_staff.proto\x1a%rapid/staff_api/v1/model_tenant.proto\"\xae\x01\n" +
	"\rSignUpRequest\x12\x1f\n" +
	"\vtenant_name\x18\x01 \x01(\tR\n" +
	"tenantName\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12$\n" +
	"\x0eimage_asset_id\x18\x03 \x01(\tR\fimageAssetId:3\x92A0\n" +
	".\xd2\x01\vtenant_name\xd2\x01\fdisplay_name\xd2\x01\x0eimage_asset_id\"P\n" +
	"\x0eSignUpResponse\x12/\n" +
	"\x05staff\x18\x01 \x01(\v2\x19.rapid.staff_api.v1.StaffR\x05staff:\r\x92A\n" +
	"\n" +
	"\b\xd2\x01\x05staff\"\x0e\n" +
	"\fGetMeRequest\"O\n" +
	"\rGetMeResponse\x12/\n" +
	"\x05staff\x18\x01 \x01(\v2\x19.rapid.staff_api.v1.StaffR\x05staff:\r\x92A\n" +
	"\n" +
	"\b\xd2\x01\x05staff\"\x14\n" +
	"\x12GetMeTenantRequest\"Y\n" +
	"\x13GetMeTenantResponse\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.rapid.staff_api.v1.TenantR\x06tenant:\x0e\x92A\v\n" +
	"\t\xd2\x01\x06tenant\"\x88\x01\n" +
	"\x0fUpdateMeRequest\x12&\n" +
	"\fdisplay_name\x18\x01 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12)\n" +
	"\x0eimage_asset_id\x18\x02 \x01(\tH\x01R\fimageAssetId\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\x11\n" +
	"\x0f_image_asset_id\"R\n" +
	"\x10UpdateMeResponse\x12/\n" +
	"\x05staff\x18\x01 \x01(\v2\x19.rapid.staff_api.v1.StaffR\x05staff:\r\x92A\n" +
	"\n" +
	"\b\xd2\x01\x05staff\"9\n" +
	"\x15UpdateMeTenantRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"\\\n" +
	"\x16UpdateMeTenantResponse\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.rapid.staff_api.v1.TenantR\x06tenant:\x0e\x92A\v\n" +
	"\t\xd2\x01\x06tenantB\xec\x01\n" +
	"\x16com.rapid.staff_api.v1B\n" +
	"ApiMeProtoP\x01Z`github.com/abyssparanoia/rapid-go/internal/infrastructure/grpc/pb/rapid/staff_api/v1;staff_apiv1\xa2\x02\x03RSX\xaa\x02\x11Rapid.StaffApi.V1\xca\x02\x11Rapid\\StaffApi\\V1\xe2\x02\x1dRapid\\StaffApi\\V1\\GPBMetadata\xea\x02\x13Rapid::StaffApi::V1b\x06proto3"

var (
	file_rapid_staff_api_v1_api_me_proto_rawDescOnce sync.Once
	file_rapid_staff_api_v1_api_me_proto_rawDescData []byte
)

func file_rapid_staff_api_v1_api_me_proto_rawDescGZIP() []byte {
	file_rapid_staff_api_v1_api_me_proto_rawDescOnce.Do(func() {
		file_rapid_staff_api_v1_api_me_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rapid_staff_api_v1_api_me_proto_rawDesc), len(file_rapid_staff_api_v1_api_me_proto_rawDesc)))
	})
	return file_rapid_staff_api_v1_api_me_proto_rawDescData
}

var file_rapid_staff_api_v1_api_me_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rapid_staff_api_v1_api_me_proto_goTypes = []any{
	(*SignUpRequest)(nil),          // 0: rapid.staff_api.v1.SignUpRequest
	(*SignUpResponse)(nil),         // 1: rapid.staff_api.v1.SignUpResponse
	(*GetMeRequest)(nil),           // 2: rapid.staff_api.v1.GetMeRequest
	(*GetMeResponse)(nil),          // 3: rapid.staff_api.v1.GetMeResponse
	(*GetMeTenantRequest)(nil),     // 4: rapid.staff_api.v1.GetMeTenantRequest
	(*GetMeTenantResponse)(nil),    // 5: rapid.staff_api.v1.GetMeTenantResponse
	(*UpdateMeRequest)(nil),        // 6: rapid.staff_api.v1.UpdateMeRequest
	(*UpdateMeResponse)(nil),       // 7: rapid.staff_api.v1.UpdateMeResponse
	(*UpdateMeTenantRequest)(nil),  // 8: rapid.staff_api.v1.UpdateMeTenantRequest
	(*UpdateMeTenantResponse)(nil), // 9: rapid.staff_api.v1.UpdateMeTenantResponse
	(*Staff)(nil),                  // 10: rapid.staff_api.v1.Staff
	(*Tenant)(nil),                 // 11: rapid.staff_api.v1.Tenant
}
var file_rapid_staff_api_v1_api_me_proto_depIdxs = []int32{
	10, // 0: rapid.staff_api.v1.SignUpResponse.staff:type_name -> rapid.staff_api.v1.Staff
	10, // 1: rapid.staff_api.v1.GetMeResponse.staff:type_name -> rapid.staff_api.v1.Staff
	11, // 2: rapid.staff_api.v1.GetMeTenantResponse.tenant:type_name -> rapid.staff_api.v1.Tenant
	10, // 3: rapid.staff_api.v1.UpdateMeResponse.staff:type_name -> rapid.staff_api.v1.Staff
	11, // 4: rapid.staff_api.v1.UpdateMeTenantResponse.tenant:type_name -> rapid.staff_api.v1.Tenant
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rapid_staff_api_v1_api_me_proto_init() }
func file_rapid_staff_api_v1_api_me_proto_init() {
	if File_rapid_staff_api_v1_api_me_proto != nil {
		return
	}
	file_rapid_staff_api_v1_model_staff_proto_init()
	file_rapid_staff_api_v1_model_tenant_proto_init()
	file_rapid_staff_api_v1_api_me_proto_msgTypes[6].OneofWrappers = []any{}
	file_rapid_staff_api_v1_api_me_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rapid_staff_api_v1_api_me_proto_rawDesc), len(file_rapid_staff_api_v1_api_me_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rapid_staff_api_v1_api_me_proto_goTypes,
		DependencyIndexes: file_rapid_staff_api_v1_api_me_proto_depIdxs,
		MessageInfos:      file_rapid_staff_api_v1_api_me_proto_msgTypes,
	}.Build()
	File_rapid_staff_api_v1_api_me_proto = out.File
	file_rapid_staff_api_v1_api_me_proto_goTypes = nil
	file_rapid_staff_api_v1_api_me_proto_depIdxs = nil
}
