// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: rapid/admin_api/v1/model_asset.proto

package admin_apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED AssetType = 0
	AssetType_ASSET_TYPE_USER_IMAGE  AssetType = 1
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_UNSPECIFIED",
		1: "ASSET_TYPE_USER_IMAGE",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED": 0,
		"ASSET_TYPE_USER_IMAGE":  1,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_rapid_admin_api_v1_model_asset_proto_enumTypes[0].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_rapid_admin_api_v1_model_asset_proto_enumTypes[0]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_rapid_admin_api_v1_model_asset_proto_rawDescGZIP(), []int{0}
}

type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNSPECIFIED     ContentType = 0
	ContentType_CONTENT_TYPE_IMAGE_PNG       ContentType = 1
	ContentType_CONTENT_TYPE_IMAGE_JPEG      ContentType = 2
	ContentType_CONTENT_TYPE_APPLICATION_ZIP ContentType = 3
	ContentType_CONTENT_TYPE_APPLICATION_PDF ContentType = 4
	ContentType_CONTENT_TYPE_TEXT_CSV        ContentType = 5
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "CONTENT_TYPE_IMAGE_PNG",
		2: "CONTENT_TYPE_IMAGE_JPEG",
		3: "CONTENT_TYPE_APPLICATION_ZIP",
		4: "CONTENT_TYPE_APPLICATION_PDF",
		5: "CONTENT_TYPE_TEXT_CSV",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED":     0,
		"CONTENT_TYPE_IMAGE_PNG":       1,
		"CONTENT_TYPE_IMAGE_JPEG":      2,
		"CONTENT_TYPE_APPLICATION_ZIP": 3,
		"CONTENT_TYPE_APPLICATION_PDF": 4,
		"CONTENT_TYPE_TEXT_CSV":        5,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_rapid_admin_api_v1_model_asset_proto_enumTypes[1].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_rapid_admin_api_v1_model_asset_proto_enumTypes[1]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_rapid_admin_api_v1_model_asset_proto_rawDescGZIP(), []int{1}
}

var File_rapid_admin_api_v1_model_asset_proto protoreflect.FileDescriptor

const file_rapid_admin_api_v1_model_asset_proto_rawDesc = "" +
	"\n" +
	"$rapid/admin_api/v1/model_asset.proto\x12\x12rapid.admin_api.v1*B\n" +
	"\tAssetType\x12\x1a\n" +
	"\x16ASSET_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ASSET_TYPE_USER_IMAGE\x10\x01*\xc3\x01\n" +
	"\vContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CONTENT_TYPE_IMAGE_PNG\x10\x01\x12\x1b\n" +
	"\x17CONTENT_TYPE_IMAGE_JPEG\x10\x02\x12 \n" +
	"\x1cCONTENT_TYPE_APPLICATION_ZIP\x10\x03\x12 \n" +
	"\x1cCONTENT_TYPE_APPLICATION_PDF\x10\x04\x12\x19\n" +
	"\x15CONTENT_TYPE_TEXT_CSV\x10\x05B\xf1\x01\n" +
	"\x16com.rapid.admin_api.v1B\x0fModelAssetProtoP\x01Z`github.com/abyssparanoia/rapid-go/internal/infrastructure/grpc/pb/rapid/admin_api/v1;admin_apiv1\xa2\x02\x03RAX\xaa\x02\x11Rapid.AdminApi.V1\xca\x02\x11Rapid\\AdminApi\\V1\xe2\x02\x1dRapid\\AdminApi\\V1\\GPBMetadata\xea\x02\x13Rapid::AdminApi::V1b\x06proto3"

var (
	file_rapid_admin_api_v1_model_asset_proto_rawDescOnce sync.Once
	file_rapid_admin_api_v1_model_asset_proto_rawDescData []byte
)

func file_rapid_admin_api_v1_model_asset_proto_rawDescGZIP() []byte {
	file_rapid_admin_api_v1_model_asset_proto_rawDescOnce.Do(func() {
		file_rapid_admin_api_v1_model_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rapid_admin_api_v1_model_asset_proto_rawDesc), len(file_rapid_admin_api_v1_model_asset_proto_rawDesc)))
	})
	return file_rapid_admin_api_v1_model_asset_proto_rawDescData
}

var file_rapid_admin_api_v1_model_asset_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rapid_admin_api_v1_model_asset_proto_goTypes = []any{
	(AssetType)(0),   // 0: rapid.admin_api.v1.AssetType
	(ContentType)(0), // 1: rapid.admin_api.v1.ContentType
}
var file_rapid_admin_api_v1_model_asset_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rapid_admin_api_v1_model_asset_proto_init() }
func file_rapid_admin_api_v1_model_asset_proto_init() {
	if File_rapid_admin_api_v1_model_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rapid_admin_api_v1_model_asset_proto_rawDesc), len(file_rapid_admin_api_v1_model_asset_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rapid_admin_api_v1_model_asset_proto_goTypes,
		DependencyIndexes: file_rapid_admin_api_v1_model_asset_proto_depIdxs,
		EnumInfos:         file_rapid_admin_api_v1_model_asset_proto_enumTypes,
	}.Build()
	File_rapid_admin_api_v1_model_asset_proto = out.File
	file_rapid_admin_api_v1_model_asset_proto_goTypes = nil
	file_rapid_admin_api_v1_model_asset_proto_depIdxs = nil
}
