// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: rapid/admin_api/v1/model_staff.proto

package admin_apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StaffRole int32

const (
	StaffRole_STAFF_ROLE_UNSPECIFIED StaffRole = 0
	StaffRole_STAFF_ROLE_NORMAL      StaffRole = 1
	StaffRole_STAFF_ROLE_ADMIN       StaffRole = 2
)

// Enum value maps for StaffRole.
var (
	StaffRole_name = map[int32]string{
		0: "STAFF_ROLE_UNSPECIFIED",
		1: "STAFF_ROLE_NORMAL",
		2: "STAFF_ROLE_ADMIN",
	}
	StaffRole_value = map[string]int32{
		"STAFF_ROLE_UNSPECIFIED": 0,
		"STAFF_ROLE_NORMAL":      1,
		"STAFF_ROLE_ADMIN":       2,
	}
)

func (x StaffRole) Enum() *StaffRole {
	p := new(StaffRole)
	*p = x
	return p
}

func (x StaffRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StaffRole) Descriptor() protoreflect.EnumDescriptor {
	return file_rapid_admin_api_v1_model_staff_proto_enumTypes[0].Descriptor()
}

func (StaffRole) Type() protoreflect.EnumType {
	return &file_rapid_admin_api_v1_model_staff_proto_enumTypes[0]
}

func (x StaffRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StaffRole.Descriptor instead.
func (StaffRole) EnumDescriptor() ([]byte, []int) {
	return file_rapid_admin_api_v1_model_staff_proto_rawDescGZIP(), []int{0}
}

type Staff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Role          StaffRole              `protobuf:"varint,3,opt,name=role,proto3,enum=rapid.admin_api.v1.StaffRole" json:"role,omitempty"`
	AuthUid       string                 `protobuf:"bytes,4,opt,name=auth_uid,json=authUid,proto3" json:"auth_uid,omitempty"`
	DisplayName   string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Tenant        *Tenant                `protobuf:"bytes,101,opt,name=tenant,proto3,oneof" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Staff) Reset() {
	*x = Staff{}
	mi := &file_rapid_admin_api_v1_model_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Staff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staff) ProtoMessage() {}

func (x *Staff) ProtoReflect() protoreflect.Message {
	mi := &file_rapid_admin_api_v1_model_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staff.ProtoReflect.Descriptor instead.
func (*Staff) Descriptor() ([]byte, []int) {
	return file_rapid_admin_api_v1_model_staff_proto_rawDescGZIP(), []int{0}
}

func (x *Staff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Staff) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Staff) GetRole() StaffRole {
	if x != nil {
		return x.Role
	}
	return StaffRole_STAFF_ROLE_UNSPECIFIED
}

func (x *Staff) GetAuthUid() string {
	if x != nil {
		return x.AuthUid
	}
	return ""
}

func (x *Staff) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Staff) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Staff) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Staff) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Staff) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Staff) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

var File_rapid_admin_api_v1_model_staff_proto protoreflect.FileDescriptor

const file_rapid_admin_api_v1_model_staff_proto_rawDesc = "" +
	"\n" +
	"$rapid/admin_api/v1/model_staff.proto\x12\x12rapid.admin_api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a%rapid/admin_api/v1/model_tenant.proto\"\xf9\x03\n" +
	"\x05Staff\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x121\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1d.rapid.admin_api.v1.StaffRoleR\x04role\x12\x19\n" +
	"\bauth_uid\x18\x04 \x01(\tR\aauthUid\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\x06tenant\x18e \x01(\v2\x1a.rapid.admin_api.v1.TenantH\x00R\x06tenant\x88\x01\x01:e\x92Ab\n" +
	"`\xd2\x01\x02id\xd2\x01\ttenant_id\xd2\x01\x04role\xd2\x01\bauth_uid\xd2\x01\fdisplay_name\xd2\x01\timage_url\xd2\x01\x05email\xd2\x01\n" +
	"created_at\xd2\x01\n" +
	"updated_atB\t\n" +
	"\a_tenant*T\n" +
	"\tStaffRole\x12\x1a\n" +
	"\x16STAFF_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11STAFF_ROLE_NORMAL\x10\x01\x12\x14\n" +
	"\x10STAFF_ROLE_ADMIN\x10\x02B\xf1\x01\n" +
	"\x16com.rapid.admin_api.v1B\x0fModelStaffProtoP\x01Z`github.com/abyssparanoia/rapid-go/internal/infrastructure/grpc/pb/rapid/admin_api/v1;admin_apiv1\xa2\x02\x03RAX\xaa\x02\x11Rapid.AdminApi.V1\xca\x02\x11Rapid\\AdminApi\\V1\xe2\x02\x1dRapid\\AdminApi\\V1\\GPBMetadata\xea\x02\x13Rapid::AdminApi::V1b\x06proto3"

var (
	file_rapid_admin_api_v1_model_staff_proto_rawDescOnce sync.Once
	file_rapid_admin_api_v1_model_staff_proto_rawDescData []byte
)

func file_rapid_admin_api_v1_model_staff_proto_rawDescGZIP() []byte {
	file_rapid_admin_api_v1_model_staff_proto_rawDescOnce.Do(func() {
		file_rapid_admin_api_v1_model_staff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rapid_admin_api_v1_model_staff_proto_rawDesc), len(file_rapid_admin_api_v1_model_staff_proto_rawDesc)))
	})
	return file_rapid_admin_api_v1_model_staff_proto_rawDescData
}

var file_rapid_admin_api_v1_model_staff_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rapid_admin_api_v1_model_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rapid_admin_api_v1_model_staff_proto_goTypes = []any{
	(StaffRole)(0),                // 0: rapid.admin_api.v1.StaffRole
	(*Staff)(nil),                 // 1: rapid.admin_api.v1.Staff
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Tenant)(nil),                // 3: rapid.admin_api.v1.Tenant
}
var file_rapid_admin_api_v1_model_staff_proto_depIdxs = []int32{
	0, // 0: rapid.admin_api.v1.Staff.role:type_name -> rapid.admin_api.v1.StaffRole
	2, // 1: rapid.admin_api.v1.Staff.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: rapid.admin_api.v1.Staff.updated_at:type_name -> google.protobuf.Timestamp
	3, // 3: rapid.admin_api.v1.Staff.tenant:type_name -> rapid.admin_api.v1.Tenant
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rapid_admin_api_v1_model_staff_proto_init() }
func file_rapid_admin_api_v1_model_staff_proto_init() {
	if File_rapid_admin_api_v1_model_staff_proto != nil {
		return
	}
	file_rapid_admin_api_v1_model_tenant_proto_init()
	file_rapid_admin_api_v1_model_staff_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rapid_admin_api_v1_model_staff_proto_rawDesc), len(file_rapid_admin_api_v1_model_staff_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rapid_admin_api_v1_model_staff_proto_goTypes,
		DependencyIndexes: file_rapid_admin_api_v1_model_staff_proto_depIdxs,
		EnumInfos:         file_rapid_admin_api_v1_model_staff_proto_enumTypes,
		MessageInfos:      file_rapid_admin_api_v1_model_staff_proto_msgTypes,
	}.Build()
	File_rapid_admin_api_v1_model_staff_proto = out.File
	file_rapid_admin_api_v1_model_staff_proto_goTypes = nil
	file_rapid_admin_api_v1_model_staff_proto_depIdxs = nil
}
