// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package public_apiv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PublicV1ServiceClient is the client API for PublicV1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicV1ServiceClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error)
}

type publicV1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicV1ServiceClient(cc grpc.ClientConnInterface) PublicV1ServiceClient {
	return &publicV1ServiceClient{cc}
}

func (c *publicV1ServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/mmg.public_api.v1.PublicV1Service/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicV1ServiceClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error) {
	out := new(GetTenantResponse)
	err := c.cc.Invoke(ctx, "/mmg.public_api.v1.PublicV1Service/GetTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicV1ServiceServer is the server API for PublicV1Service service.
// All implementations should embed UnimplementedPublicV1ServiceServer
// for forward compatibility
type PublicV1ServiceServer interface {
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error)
}

// UnimplementedPublicV1ServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPublicV1ServiceServer struct {
}

func (UnimplementedPublicV1ServiceServer) SignIn(context.Context, *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedPublicV1ServiceServer) GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenant not implemented")
}

// UnsafePublicV1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicV1ServiceServer will
// result in compilation errors.
type UnsafePublicV1ServiceServer interface {
	mustEmbedUnimplementedPublicV1ServiceServer()
}

func RegisterPublicV1ServiceServer(s grpc.ServiceRegistrar, srv PublicV1ServiceServer) {
	s.RegisterService(&PublicV1Service_ServiceDesc, srv)
}

func _PublicV1Service_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicV1ServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mmg.public_api.v1.PublicV1Service/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicV1ServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicV1Service_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicV1ServiceServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mmg.public_api.v1.PublicV1Service/GetTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicV1ServiceServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicV1Service_ServiceDesc is the grpc.ServiceDesc for PublicV1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicV1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mmg.public_api.v1.PublicV1Service",
	HandlerType: (*PublicV1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _PublicV1Service_SignIn_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _PublicV1Service_GetTenant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mmg/public_api/v1/public.proto",
}
