CREATE TABLE SchemaMigrations (
  Version INT64 NOT NULL,
  Dirty BOOL NOT NULL,
) PRIMARY KEY(Version);

CREATE TABLE Tenants (
  TenantID STRING(36) NOT NULL,
  Name STRING(256) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL,
  UpdatedAt TIMESTAMP NOT NULL,
) PRIMARY KEY(TenantID);

CREATE TABLE StaffRoles (
  StaffRoleID STRING(32) NOT NULL,
) PRIMARY KEY(StaffRoleID);

CREATE TABLE Staffs (
  StaffID STRING(36) NOT NULL,
  TenantID STRING(36) NOT NULL,
  Role STRING(32) NOT NULL,
  AuthUID STRING(256) NOT NULL,
  DisplayName STRING(256) NOT NULL,
  ImagePath STRING(MAX) NOT NULL,
  Email STRING(512) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL,
  UpdatedAt TIMESTAMP NOT NULL,
  CONSTRAINT Staffs_FK_TenantID FOREIGN KEY(TenantID) REFERENCES Tenants(TenantID) ON DELETE NO ACTION,
  CONSTRAINT Staffs_FK_Role FOREIGN KEY(Role) REFERENCES StaffRoles(StaffRoleID) ON DELETE NO ACTION,
) PRIMARY KEY(StaffID);
