// Code generated by MockGen. DO NOT EDIT.
// Source: admin_authentication.go
//
// Generated by this command:
//
//	mockgen -source=admin_authentication.go -destination=mock/admin_authentication.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	model "github.com/abyssparanoia/rapid-go/internal/domain/model"
	repository "github.com/abyssparanoia/rapid-go/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminAuthentication is a mock of AdminAuthentication interface.
type MockAdminAuthentication struct {
	ctrl     *gomock.Controller
	recorder *MockAdminAuthenticationMockRecorder
	isgomock struct{}
}

// MockAdminAuthenticationMockRecorder is the mock recorder for MockAdminAuthentication.
type MockAdminAuthenticationMockRecorder struct {
	mock *MockAdminAuthentication
}

// NewMockAdminAuthentication creates a new mock instance.
func NewMockAdminAuthentication(ctrl *gomock.Controller) *MockAdminAuthentication {
	mock := &MockAdminAuthentication{ctrl: ctrl}
	mock.recorder = &MockAdminAuthenticationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminAuthentication) EXPECT() *MockAdminAuthenticationMockRecorder {
	return m.recorder
}

// CreateCustomToken mocks base method.
func (m *MockAdminAuthentication) CreateCustomToken(ctx context.Context, authUID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomToken", ctx, authUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomToken indicates an expected call of CreateCustomToken.
func (mr *MockAdminAuthenticationMockRecorder) CreateCustomToken(ctx, authUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomToken", reflect.TypeOf((*MockAdminAuthentication)(nil).CreateCustomToken), ctx, authUID)
}

// CreateIDToken mocks base method.
func (m *MockAdminAuthentication) CreateIDToken(ctx context.Context, authUID, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIDToken", ctx, authUID, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIDToken indicates an expected call of CreateIDToken.
func (mr *MockAdminAuthenticationMockRecorder) CreateIDToken(ctx, authUID, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIDToken", reflect.TypeOf((*MockAdminAuthentication)(nil).CreateIDToken), ctx, authUID, password)
}

// CreateUser mocks base method.
func (m *MockAdminAuthentication) CreateUser(ctx context.Context, param repository.AdminAuthenticationCreateUserParam) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, param)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAdminAuthenticationMockRecorder) CreateUser(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAdminAuthentication)(nil).CreateUser), ctx, param)
}

// GetUserByEmail mocks base method.
func (m *MockAdminAuthentication) GetUserByEmail(ctx context.Context, email string) (*repository.AdminAuthenticationGetUserByEmailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*repository.AdminAuthenticationGetUserByEmailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockAdminAuthenticationMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockAdminAuthentication)(nil).GetUserByEmail), ctx, email)
}

// StoreClaims mocks base method.
func (m *MockAdminAuthentication) StoreClaims(ctx context.Context, authUID string, adminClaims *model.AdminClaims) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreClaims", ctx, authUID, adminClaims)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreClaims indicates an expected call of StoreClaims.
func (mr *MockAdminAuthenticationMockRecorder) StoreClaims(ctx, authUID, adminClaims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreClaims", reflect.TypeOf((*MockAdminAuthentication)(nil).StoreClaims), ctx, authUID, adminClaims)
}

// VerifyIDToken mocks base method.
func (m *MockAdminAuthentication) VerifyIDToken(ctx context.Context, idToken string) (*model.AdminClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIDToken", ctx, idToken)
	ret0, _ := ret[0].(*model.AdminClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyIDToken indicates an expected call of VerifyIDToken.
func (mr *MockAdminAuthenticationMockRecorder) VerifyIDToken(ctx, idToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIDToken", reflect.TypeOf((*MockAdminAuthentication)(nil).VerifyIDToken), ctx, idToken)
}
