CREATE TABLE "public"."asset_types" (
    "id" character varying(256) NOT NULL,
    CONSTRAINT "asset_types_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."assets" (
    "id" character varying(64) NOT NULL,
    "content_type" character varying(256) NOT NULL,
    "type" character varying(256) NOT NULL,
    "path" text NOT NULL,
    "expires_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    CONSTRAINT "assets_fkey_content_type" FOREIGN KEY (content_type) REFERENCES content_types(id),
    CONSTRAINT "assets_fkey_type" FOREIGN KEY (type) REFERENCES asset_types(id),
    CONSTRAINT "assets_pkey" PRIMARY KEY (id)
);

CREATE INDEX assets_idx_content_type ON assets USING btree (content_type);

CREATE INDEX assets_idx_type ON assets USING btree (type);

CREATE TABLE "public"."content_types" (
    "id" character varying(256) NOT NULL,
    CONSTRAINT "content_types_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."goose_db_version" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "version_id" bigint NOT NULL,
    "is_applied" boolean NOT NULL,
    "tstamp" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "goose_db_version_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."staff_roles" (
    "id" character varying(32) NOT NULL,
    CONSTRAINT "staff_roles_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."staffs" (
    "id" character varying(64) NOT NULL,
    "tenant_id" character varying(64) NOT NULL,
    "role" character varying(32) NOT NULL,
    "auth_uid" character varying(256) NOT NULL,
    "display_name" character varying(256) NOT NULL,
    "image_path" character varying(1024) NOT NULL,
    "email" character varying(512) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    CONSTRAINT "staffs_fkey_role" FOREIGN KEY (role) REFERENCES staff_roles(id),
    CONSTRAINT "staffs_fkey_tenant_id" FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT "staffs_pkey" PRIMARY KEY (id),
    CONSTRAINT "staffs_unique_auth_uid" UNIQUE (auth_uid),
    CONSTRAINT "staffs_unique_email" UNIQUE (email)
);

CREATE INDEX staffs_idx_role ON staffs USING btree (role);

CREATE INDEX staffs_idx_tenant_id ON staffs USING btree (tenant_id);

CREATE TABLE "public"."tenants" (
    "id" character varying(64) NOT NULL,
    "name" character varying(256) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    CONSTRAINT "tenants_pkey" PRIMARY KEY (id)
);

